spring:
  application:
    name: kiss
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST_PORT}/${DATABASE_DB}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  config:
    import:
      - file:.env[.properties]
      - classpath:jimmer.yml
server:
  port: ${APPLICATION_PORT}
  servlet:
    session:
      cookie:
        secure: true
        same-site: none
        http-only: true
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
